// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AzraelAccountAction } from "./AzraelAccountAction";

export type AzraelAccountParams = { action: AzraelAccountAction, profileId?: string | null, loginId?: string | null, includeDetails?: boolean, };
