// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { AzraelProfile } from "./AzraelProfile";

export type AzraelAccountState = { instanceId: string, revision: number, codexHome: string, profiles: Array<AzraelProfile>, currentAccount: Account | null, activeProfileId: string | null, pendingProfileId: string | null, isSwitching: boolean, hasActiveTurns: boolean, loginPending: boolean, lastError: string | null, };
