// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AzraelUsageWindowStatus } from "./AzraelUsageWindowStatus";

export type AzraelUsageWindowSchedule = { profileId: string, workspaceAccountId: string, userId: string, enabled: boolean, nextRunAt: bigint | null, basisResetAt: bigint | null, lastAttemptAt: bigint | null, status: AzraelUsageWindowStatus, error: string | null, };
