// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AzraelAccountState } from "./AzraelAccountState";
import type { AzraelLogin } from "./AzraelLogin";
import type { ConsumeAccountRateLimitResetCreditOutcome } from "./ConsumeAccountRateLimitResetCreditOutcome";
import type { GetAccountRateLimitsResponse } from "./GetAccountRateLimitsResponse";

export type AzraelAccountResponse = { state: AzraelAccountState, login: AzraelLogin | null, usage: GetAccountRateLimitsResponse | null, usageProfileId: string | null, resetCreditOutcome?: ConsumeAccountRateLimitResetCreditOutcome | null, };
