// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted Computer Use tool mode; unknown values fail deserialization.
 */
export type ComputerUseMode = "selectedWindow";
