// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderCatalogState } from "./ProviderCatalogState";

export type ProviderCatalogStatus = { providerId: string, state: ProviderCatalogState, modelCount: number, observedAt: number, errorCode?: string, };
