// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueuedSubmissionKind } from "./QueuedSubmissionKind";
import type { UserInput } from "./UserInput";

export type QueuedSubmission = { id: string, kind: QueuedSubmissionKind, input: Array<UserInput>, clientUserMessageId: string, };
