// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootResumeAction } from "./RootResumeAction";

export type RootResumeParams = { action: RootResumeAction, reservationId?: string | null, revision?: bigint | null, };
