// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PricingStatus } from "./PricingStatus";

export type ContextPricing = { status: PricingStatus, inputTokenThreshold: number | null, inclusive: boolean, sourceUrl: string | null, };
