// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoCompactSource } from "./AutoCompactSource";
import type { ContextPricing } from "./ContextPricing";

export type ContextPolicy = { providerId: string, modelId: string, contextWindow: number | null, safeContextWindow: number | null, autoCompactBaseTokens: number | null, autoCompactTokenLimit: number | null, autoCompactSource: AutoCompactSource, pricing: ContextPricing, inputTokens: number | null, inputTokensEstimated: boolean, };
