// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A present empty entry selects the dynamic default, independently of global settings.
 */
export type ProviderAutoCompact = { percentage: number | null, token_limit: number | null, };
