// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootResumeAgentTask } from "./RootResumeAgentTask";
import type { RootResumeState } from "./RootResumeState";
import type { RootResumeWakeReason } from "./RootResumeWakeReason";
import type { JsonValue } from "./serde_json/JsonValue";

export type RootResumeReservation = { id: string, rootThreadId: string, originatingTurnId: string, rootTurnId: string, callId: string, resumeTurnId: string, resumeAtMs: bigint, createdAtMs: bigint, updatedAtMs: bigint, waitStartedAtMs: bigint | null, waitEndedAtMs: bigint | null, revision: bigint, state: RootResumeState, agentTasks: Array<RootResumeAgentTask>, completionTasks: Array<string>, reason: string, finalOutputJsonSchema: JsonValue | null, wakeReason: RootResumeWakeReason | null, lastError: string | null, };
