// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RootResumeState } from "./RootResumeState";

/**
 * Durable presentation metadata for the wait attached to its originating turn.
 */
export type RootResumeWait = { reservationId: string, revision: number, waitStartedAtMs: number | null, waitEndedAtMs: number | null, resumeAtMs: number, state: RootResumeState, canWakeEarly: boolean, };
